### ISSUE TITLE
Update hooks package to match SDK package

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#26]
Related to https://app.skiff.com/file/dae78141-479a-4849-8ead-0e54331e56d7 and https://app.skiff.com/file/4a84419b-e4ba-42fc-80bb-bbdedff3fee9
Trello card: https://trello.com/c/3eVyIRGc/183-organize-tasks-for-sdk-in-trello-for-management

### Remove dependencies to session context

- [x] Remove set cookie from hooks (in `useAuthentication` I think). Remove need for CookieProvider https://github.com/liteflow-labs/nft/pull/2077
- [x] Move to components/app: https://github.com/liteflow-labs/liteflow-js/pull/90
  - [x] COOKIE_JWT_TOKEN https://github.com/liteflow-labs/nft/pull/2077
  - [x] useSession
  - [x] SessionContext & ISessionContext

### Remove from export
- [x] useCheckOwnership
- [x] useIPFSUploader https://github.com/liteflow-labs/nft/pull/2107

### To move out of hooks package or to remove if not used
Also simplify the code source if possible
- [ ] useAddFund
- [x] useAssetOwnerQuantity https://github.com/liteflow-labs/nft/pull/2075
- [ ] useAuctionStatus
- [ ] useBalance (also remove API if possible)
- [x] useBlockExplorer & BlockExplorer https://github.com/liteflow-labs/nft/pull/2107
- [x] useCreateComment (move to o-mee) https://github.com/liteflow-labs/nft/pull/2107
- [x] useErrorFormatter: https://github.com/liteflow-labs/nft/pull/2107
- [ ] formatError
- [x] useExecuteOnAccountChange https://github.com/liteflow-labs/nft/pull/2107
- [ ] `useExecuteOnAccountChange` hook seems to be misused because it executes the refetch on query that are not related to user:
  - [ ] https://github.com/liteflow-labs/nft/blob/90cb40219b7a4ffed944647122f82e7fc2659cc2/packages/templates/src/home/Explorer.tsx#L327-L336
  - [ ] https://github.com/liteflow-labs/nft/blob/90cb40219b7a4ffed944647122f82e7fc2659cc2/packages/templates/src/offers/Bid.tsx#L123-L129
  - [ ] https://github.com/liteflow-labs/nft/blob/90cb40219b7a4ffed944647122f82e7fc2659cc2/packages/templates/src/offers/Checkout.tsx#L108-L114
- Seems to be unnecessary if variable `address` of the related query is obtained from `useSession` (maybe prone to flickering on refresh (SSR vs client re-rendering):
  - [ ] https://github.com/liteflow-labs/nft/blob/90cb40219b7a4ffed944647122f82e7fc2659cc2/packages/templates/src/user/CreatedAssets.tsx#L107-L116
  - [ ] https://github.com/liteflow-labs/nft/blob/90cb40219b7a4ffed944647122f82e7fc2659cc2/packages/templates/src/user/OnSaleAssets.tsx#L107-L116
  - [ ] https://github.com/liteflow-labs/nft/blob/90cb40219b7a4ffed944647122f82e7fc2659cc2/packages/templates/src/user/OwnedAssets.tsx#L110-L119
- [x] useFileTransformer https://github.com/liteflow-labs/nft/pull/2107
- [x] useFormatAddress https://github.com/liteflow-labs/nft/pull/2107
- [ ] formatAddress
- [x] useIsAssetOwner https://github.com/liteflow-labs/nft/pull/2075
- [x] useLike (move to o-mee) https://github.com/liteflow-labs/nft/pull/2107
- [x] useLocalFileURL https://github.com/liteflow-labs/nft/pull/2107
- [x] useLoginRedirect https://github.com/liteflow-labs/nft/pull/2107
- [x] useNow https://github.com/liteflow-labs/nft/pull/2107
- [x] useOrderById https://github.com/liteflow-labs/nft/pull/2107
- [x] useOwnAllSupply https://github.com/liteflow-labs/nft/pull/2075
- [x] usePaginate https://github.com/liteflow-labs/nft/pull/2107
- [x] useParsePrice: https://github.com/liteflow-labs/nft/pull/2107
- [x] parsePrice: https://github.com/liteflow-labs/liteflow-js/issues/101
  - [x] Remove `bignumber.js` deps from hook once done: https://github.com/liteflow-labs/libraries/issues/29
- [ ] isSameAddress
- [ ] dateFromNow
- [ ] formatDate
- [ ] formatDateDatetime
- [ ] getHumanizedDate
- [ ] formatSocial
- [ ] removeEmptyFromObject
- [x] useIsLoggedIn https://github.com/liteflow-labs/liteflow-js/pull/90
- [x] useActivateWallet https://github.com/liteflow-labs/liteflow-js/pull/90
- [x] useEagerConnect https://github.com/liteflow-labs/liteflow-js/pull/90
- [x] useSigner https://github.com/liteflow-labs/liteflow-js/pull/90

### Remove useWeb3React dep:
- [x] Once, useActivateWallet, useEagerConnect, useSession, and useSigner have been moved, the dep can be removed https://github.com/liteflow-labs/liteflow-js/pull/90

### Remove Apollo dep
- [x] Need to replace Apollo client by a light client like https://github.com/prisma-labs/graphql-request https://github.com/liteflow-labs/nft/pull/2120
- [x] Need to introduce a new context https://github.com/liteflow-labs/nft/pull/2120
  - For the API url
  - maybe the JWT token until the backend is fully updated with signature per action

### Improve Hooks API
- [x] Create new provider to get the require config https://github.com/liteflow-labs/nft/pull/2120
- [ ] Improve API of hooks. Need to normalise them
